name = "AerostructuralDynamics"
uuid = "903f4ae0-4fef-4d1a-a7b0-612989f7a972"
authors = ["Taylor McDonnell <taylor.golden.mcdonnell@gmail.com> and contributors"]
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GXBeam = "974624c9-1acb-4ad6-a627-8ac40fc27a3e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
DifferentialEquations = "6.17"
LinearMaps = "3.3"
StaticArrays = "0.12, 1.0"
julia = "1.6"
